site_name: Leo's Cheatsheets
theme:
  name: material
  font:
    code: Roboto markdown_extensions
  palette:
    - scheme: default
      primary: purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.expand
    - search.highlight
    - dark_mode

nav:
  - Home: "index.md"
  - Machine Learning:
      - Machine Learning kurz & gut:
          - Overview: "machine-learning-kurz-und-gut/overview.md"
          - 2.1 Linear Regression: "machine-learning-kurz-und-gut/2_1-linear-regression.md"
  - Frameworks:
      - Vue & Nuxt:
          - Basics of Vue: "frameworks/vue-nuxt/basics-of-vue.md"
          - Basics of Nuxt: "frameworks/vue-nuxt/basics-of-nuxt.md"
      - Symfony:
          - Basics of Symfony: "frameworks/symfony/basics-of-symfony.md"
  - Dangerous & Outdated:
      - Basics of Symfony: "dangerous-outdated/basics-of-symfony.md"
      - Django Deployment on Render: "dangerous-outdated/django-deployment-on-render.md"

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - mathjax/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
